spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration

jwt:
  expiration: 86400000 #1 Day

server:
  address=0.0.0.0

google:
  client-id: ${GOOGLE_CLIENT_ID}